[build]
  command = "npm install && npm run build-netlify"
  functions = "bin/netlify"

[functions]
  directory = "bin/netlify"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"